/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
	"reflect"
)


// EventLogAPIService EventLogAPI service
type EventLogAPIService service

type EventLogAPIGetEventLogRequest struct {
	ctx context.Context
	ApiService *EventLogAPIService
	eventLogId int32
}

func (r EventLogAPIGetEventLogRequest) Execute() (*EventLogResponse, *http.Response, error) {
	return r.ApiService.GetEventLogExecute(r)
}

/*
GetEventLog Get Event Log

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param eventLogId
 @return EventLogAPIGetEventLogRequest
*/
func (a *EventLogAPIService) GetEventLog(ctx context.Context, eventLogId int32) EventLogAPIGetEventLogRequest {
	return EventLogAPIGetEventLogRequest{
		ApiService: a,
		ctx: ctx,
		eventLogId: eventLogId,
	}
}

// Execute executes the request
//  @return EventLogResponse
func (a *EventLogAPIService) GetEventLogExecute(r EventLogAPIGetEventLogRequest) (*EventLogResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EventLogResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EventLogAPIService.GetEventLog")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/eventLogs/{event_log_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"event_log_id"+"}", url.PathEscape(parameterValueToString(r.eventLogId, "eventLogId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v HTTPExceptionResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v HTTPExceptionResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HTTPExceptionResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type EventLogAPIGetEventLogsRequest struct {
	ctx context.Context
	ApiService *EventLogAPIService
	limit *int32
	offset *int32
	orderBy *string
	dagId *string
	taskId *string
	runId *string
	mapIndex *int32
	tryNumber *int32
	owner *string
	event *string
	excludedEvents *[]string
	includedEvents *[]string
	before *time.Time
	after *time.Time
}

func (r EventLogAPIGetEventLogsRequest) Limit(limit int32) EventLogAPIGetEventLogsRequest {
	r.limit = &limit
	return r
}

func (r EventLogAPIGetEventLogsRequest) Offset(offset int32) EventLogAPIGetEventLogsRequest {
	r.offset = &offset
	return r
}

func (r EventLogAPIGetEventLogsRequest) OrderBy(orderBy string) EventLogAPIGetEventLogsRequest {
	r.orderBy = &orderBy
	return r
}

func (r EventLogAPIGetEventLogsRequest) DagId(dagId string) EventLogAPIGetEventLogsRequest {
	r.dagId = &dagId
	return r
}

func (r EventLogAPIGetEventLogsRequest) TaskId(taskId string) EventLogAPIGetEventLogsRequest {
	r.taskId = &taskId
	return r
}

func (r EventLogAPIGetEventLogsRequest) RunId(runId string) EventLogAPIGetEventLogsRequest {
	r.runId = &runId
	return r
}

func (r EventLogAPIGetEventLogsRequest) MapIndex(mapIndex int32) EventLogAPIGetEventLogsRequest {
	r.mapIndex = &mapIndex
	return r
}

func (r EventLogAPIGetEventLogsRequest) TryNumber(tryNumber int32) EventLogAPIGetEventLogsRequest {
	r.tryNumber = &tryNumber
	return r
}

func (r EventLogAPIGetEventLogsRequest) Owner(owner string) EventLogAPIGetEventLogsRequest {
	r.owner = &owner
	return r
}

func (r EventLogAPIGetEventLogsRequest) Event(event string) EventLogAPIGetEventLogsRequest {
	r.event = &event
	return r
}

func (r EventLogAPIGetEventLogsRequest) ExcludedEvents(excludedEvents []string) EventLogAPIGetEventLogsRequest {
	r.excludedEvents = &excludedEvents
	return r
}

func (r EventLogAPIGetEventLogsRequest) IncludedEvents(includedEvents []string) EventLogAPIGetEventLogsRequest {
	r.includedEvents = &includedEvents
	return r
}

func (r EventLogAPIGetEventLogsRequest) Before(before time.Time) EventLogAPIGetEventLogsRequest {
	r.before = &before
	return r
}

func (r EventLogAPIGetEventLogsRequest) After(after time.Time) EventLogAPIGetEventLogsRequest {
	r.after = &after
	return r
}

func (r EventLogAPIGetEventLogsRequest) Execute() (*EventLogCollectionResponse, *http.Response, error) {
	return r.ApiService.GetEventLogsExecute(r)
}

/*
GetEventLogs Get Event Logs

Get all Event Logs.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return EventLogAPIGetEventLogsRequest
*/
func (a *EventLogAPIService) GetEventLogs(ctx context.Context) EventLogAPIGetEventLogsRequest {
	return EventLogAPIGetEventLogsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EventLogCollectionResponse
func (a *EventLogAPIService) GetEventLogsExecute(r EventLogAPIGetEventLogsRequest) (*EventLogCollectionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EventLogCollectionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EventLogAPIService.GetEventLogs")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/eventLogs"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue int32 = 50
		r.limit = &defaultValue
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	} else {
		var defaultValue int32 = 0
		r.offset = &defaultValue
	}
	if r.orderBy != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "order_by", r.orderBy, "form", "")
	} else {
		var defaultValue string = "id"
		r.orderBy = &defaultValue
	}
	if r.dagId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "dag_id", r.dagId, "form", "")
	}
	if r.taskId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "task_id", r.taskId, "form", "")
	}
	if r.runId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "run_id", r.runId, "form", "")
	}
	if r.mapIndex != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "map_index", r.mapIndex, "form", "")
	}
	if r.tryNumber != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "try_number", r.tryNumber, "form", "")
	}
	if r.owner != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "owner", r.owner, "form", "")
	}
	if r.event != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "event", r.event, "form", "")
	}
	if r.excludedEvents != nil {
		t := *r.excludedEvents
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "excluded_events", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "excluded_events", t, "form", "multi")
		}
	}
	if r.includedEvents != nil {
		t := *r.includedEvents
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "included_events", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "included_events", t, "form", "multi")
		}
	}
	if r.before != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "before", r.before, "form", "")
	}
	if r.after != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "after", r.after, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v HTTPExceptionResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v HTTPExceptionResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
