/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// BulkBodyConnectionBodyActionsInner - struct for BulkBodyConnectionBodyActionsInner
type BulkBodyConnectionBodyActionsInner struct {
	BulkCreateActionConnectionBody *BulkCreateActionConnectionBody
	BulkDeleteActionConnectionBody *BulkDeleteActionConnectionBody
	BulkUpdateActionConnectionBody *BulkUpdateActionConnectionBody
}

// BulkCreateActionConnectionBodyAsBulkBodyConnectionBodyActionsInner is a convenience function that returns BulkCreateActionConnectionBody wrapped in BulkBodyConnectionBodyActionsInner
func BulkCreateActionConnectionBodyAsBulkBodyConnectionBodyActionsInner(v *BulkCreateActionConnectionBody) BulkBodyConnectionBodyActionsInner {
	return BulkBodyConnectionBodyActionsInner{
		BulkCreateActionConnectionBody: v,
	}
}

// BulkDeleteActionConnectionBodyAsBulkBodyConnectionBodyActionsInner is a convenience function that returns BulkDeleteActionConnectionBody wrapped in BulkBodyConnectionBodyActionsInner
func BulkDeleteActionConnectionBodyAsBulkBodyConnectionBodyActionsInner(v *BulkDeleteActionConnectionBody) BulkBodyConnectionBodyActionsInner {
	return BulkBodyConnectionBodyActionsInner{
		BulkDeleteActionConnectionBody: v,
	}
}

// BulkUpdateActionConnectionBodyAsBulkBodyConnectionBodyActionsInner is a convenience function that returns BulkUpdateActionConnectionBody wrapped in BulkBodyConnectionBodyActionsInner
func BulkUpdateActionConnectionBodyAsBulkBodyConnectionBodyActionsInner(v *BulkUpdateActionConnectionBody) BulkBodyConnectionBodyActionsInner {
	return BulkBodyConnectionBodyActionsInner{
		BulkUpdateActionConnectionBody: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkBodyConnectionBodyActionsInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BulkCreateActionConnectionBody
	err = newStrictDecoder(data).Decode(&dst.BulkCreateActionConnectionBody)
	if err == nil {
		jsonBulkCreateActionConnectionBody, _ := json.Marshal(dst.BulkCreateActionConnectionBody)
		if string(jsonBulkCreateActionConnectionBody) == "{}" { // empty struct
			dst.BulkCreateActionConnectionBody = nil
		} else {
			if err = validator.Validate(dst.BulkCreateActionConnectionBody); err != nil {
				dst.BulkCreateActionConnectionBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.BulkCreateActionConnectionBody = nil
	}

	// try to unmarshal data into BulkDeleteActionConnectionBody
	err = newStrictDecoder(data).Decode(&dst.BulkDeleteActionConnectionBody)
	if err == nil {
		jsonBulkDeleteActionConnectionBody, _ := json.Marshal(dst.BulkDeleteActionConnectionBody)
		if string(jsonBulkDeleteActionConnectionBody) == "{}" { // empty struct
			dst.BulkDeleteActionConnectionBody = nil
		} else {
			if err = validator.Validate(dst.BulkDeleteActionConnectionBody); err != nil {
				dst.BulkDeleteActionConnectionBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.BulkDeleteActionConnectionBody = nil
	}

	// try to unmarshal data into BulkUpdateActionConnectionBody
	err = newStrictDecoder(data).Decode(&dst.BulkUpdateActionConnectionBody)
	if err == nil {
		jsonBulkUpdateActionConnectionBody, _ := json.Marshal(dst.BulkUpdateActionConnectionBody)
		if string(jsonBulkUpdateActionConnectionBody) == "{}" { // empty struct
			dst.BulkUpdateActionConnectionBody = nil
		} else {
			if err = validator.Validate(dst.BulkUpdateActionConnectionBody); err != nil {
				dst.BulkUpdateActionConnectionBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.BulkUpdateActionConnectionBody = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BulkCreateActionConnectionBody = nil
		dst.BulkDeleteActionConnectionBody = nil
		dst.BulkUpdateActionConnectionBody = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkBodyConnectionBodyActionsInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BulkBodyConnectionBodyActionsInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkBodyConnectionBodyActionsInner) MarshalJSON() ([]byte, error) {
	if src.BulkCreateActionConnectionBody != nil {
		return json.Marshal(&src.BulkCreateActionConnectionBody)
	}

	if src.BulkDeleteActionConnectionBody != nil {
		return json.Marshal(&src.BulkDeleteActionConnectionBody)
	}

	if src.BulkUpdateActionConnectionBody != nil {
		return json.Marshal(&src.BulkUpdateActionConnectionBody)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkBodyConnectionBodyActionsInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BulkCreateActionConnectionBody != nil {
		return obj.BulkCreateActionConnectionBody
	}

	if obj.BulkDeleteActionConnectionBody != nil {
		return obj.BulkDeleteActionConnectionBody
	}

	if obj.BulkUpdateActionConnectionBody != nil {
		return obj.BulkUpdateActionConnectionBody
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkBodyConnectionBodyActionsInner) GetActualInstanceValue() (interface{}) {
	if obj.BulkCreateActionConnectionBody != nil {
		return *obj.BulkCreateActionConnectionBody
	}

	if obj.BulkDeleteActionConnectionBody != nil {
		return *obj.BulkDeleteActionConnectionBody
	}

	if obj.BulkUpdateActionConnectionBody != nil {
		return *obj.BulkUpdateActionConnectionBody
	}

	// all schemas are nil
	return nil
}

type NullableBulkBodyConnectionBodyActionsInner struct {
	value *BulkBodyConnectionBodyActionsInner
	isSet bool
}

func (v NullableBulkBodyConnectionBodyActionsInner) Get() *BulkBodyConnectionBodyActionsInner {
	return v.value
}

func (v *NullableBulkBodyConnectionBodyActionsInner) Set(val *BulkBodyConnectionBodyActionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkBodyConnectionBodyActionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkBodyConnectionBodyActionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkBodyConnectionBodyActionsInner(val *BulkBodyConnectionBodyActionsInner) *NullableBulkBodyConnectionBodyActionsInner {
	return &NullableBulkBodyConnectionBodyActionsInner{value: val, isSet: true}
}

func (v NullableBulkBodyConnectionBodyActionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkBodyConnectionBodyActionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


