/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkBodyPoolBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkBodyPoolBody{}

// BulkBodyPoolBody struct for BulkBodyPoolBody
type BulkBodyPoolBody struct {
	Actions []BulkBodyPoolBodyActionsInner `json:"actions"`
	AdditionalProperties map[string]interface{}
}

type _BulkBodyPoolBody BulkBodyPoolBody

// NewBulkBodyPoolBody instantiates a new BulkBodyPoolBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkBodyPoolBody(actions []BulkBodyPoolBodyActionsInner) *BulkBodyPoolBody {
	this := BulkBodyPoolBody{}
	this.Actions = actions
	return &this
}

// NewBulkBodyPoolBodyWithDefaults instantiates a new BulkBodyPoolBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkBodyPoolBodyWithDefaults() *BulkBodyPoolBody {
	this := BulkBodyPoolBody{}
	return &this
}

// GetActions returns the Actions field value
func (o *BulkBodyPoolBody) GetActions() []BulkBodyPoolBodyActionsInner {
	if o == nil {
		var ret []BulkBodyPoolBodyActionsInner
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *BulkBodyPoolBody) GetActionsOk() ([]BulkBodyPoolBodyActionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *BulkBodyPoolBody) SetActions(v []BulkBodyPoolBodyActionsInner) {
	o.Actions = v
}

func (o BulkBodyPoolBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkBodyPoolBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["actions"] = o.Actions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkBodyPoolBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkBodyPoolBody := _BulkBodyPoolBody{}

	err = json.Unmarshal(data, &varBulkBodyPoolBody)

	if err != nil {
		return err
	}

	*o = BulkBodyPoolBody(varBulkBodyPoolBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "actions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkBodyPoolBody struct {
	value *BulkBodyPoolBody
	isSet bool
}

func (v NullableBulkBodyPoolBody) Get() *BulkBodyPoolBody {
	return v.value
}

func (v *NullableBulkBodyPoolBody) Set(val *BulkBodyPoolBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkBodyPoolBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkBodyPoolBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkBodyPoolBody(val *BulkBodyPoolBody) *NullableBulkBodyPoolBody {
	return &NullableBulkBodyPoolBody{value: val, isSet: true}
}

func (v NullableBulkBodyPoolBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkBodyPoolBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


