/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkBodyConnectionBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkBodyConnectionBody{}

// BulkBodyConnectionBody struct for BulkBodyConnectionBody
type BulkBodyConnectionBody struct {
	Actions []BulkBodyConnectionBodyActionsInner `json:"actions"`
	AdditionalProperties map[string]interface{}
}

type _BulkBodyConnectionBody BulkBodyConnectionBody

// NewBulkBodyConnectionBody instantiates a new BulkBodyConnectionBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkBodyConnectionBody(actions []BulkBodyConnectionBodyActionsInner) *BulkBodyConnectionBody {
	this := BulkBodyConnectionBody{}
	this.Actions = actions
	return &this
}

// NewBulkBodyConnectionBodyWithDefaults instantiates a new BulkBodyConnectionBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkBodyConnectionBodyWithDefaults() *BulkBodyConnectionBody {
	this := BulkBodyConnectionBody{}
	return &this
}

// GetActions returns the Actions field value
func (o *BulkBodyConnectionBody) GetActions() []BulkBodyConnectionBodyActionsInner {
	if o == nil {
		var ret []BulkBodyConnectionBodyActionsInner
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *BulkBodyConnectionBody) GetActionsOk() ([]BulkBodyConnectionBodyActionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *BulkBodyConnectionBody) SetActions(v []BulkBodyConnectionBodyActionsInner) {
	o.Actions = v
}

func (o BulkBodyConnectionBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkBodyConnectionBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["actions"] = o.Actions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkBodyConnectionBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkBodyConnectionBody := _BulkBodyConnectionBody{}

	err = json.Unmarshal(data, &varBulkBodyConnectionBody)

	if err != nil {
		return err
	}

	*o = BulkBodyConnectionBody(varBulkBodyConnectionBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "actions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkBodyConnectionBody struct {
	value *BulkBodyConnectionBody
	isSet bool
}

func (v NullableBulkBodyConnectionBody) Get() *BulkBodyConnectionBody {
	return v.value
}

func (v *NullableBulkBodyConnectionBody) Set(val *BulkBodyConnectionBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkBodyConnectionBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkBodyConnectionBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkBodyConnectionBody(val *BulkBodyConnectionBody) *NullableBulkBodyConnectionBody {
	return &NullableBulkBodyConnectionBody{value: val, isSet: true}
}

func (v NullableBulkBodyConnectionBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkBodyConnectionBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


