/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// BulkBodyBulkTaskInstanceBodyActionsInner - struct for BulkBodyBulkTaskInstanceBodyActionsInner
type BulkBodyBulkTaskInstanceBodyActionsInner struct {
	BulkCreateActionBulkTaskInstanceBody *BulkCreateActionBulkTaskInstanceBody
	BulkDeleteActionBulkTaskInstanceBody *BulkDeleteActionBulkTaskInstanceBody
	BulkUpdateActionBulkTaskInstanceBody *BulkUpdateActionBulkTaskInstanceBody
}

// BulkCreateActionBulkTaskInstanceBodyAsBulkBodyBulkTaskInstanceBodyActionsInner is a convenience function that returns BulkCreateActionBulkTaskInstanceBody wrapped in BulkBodyBulkTaskInstanceBodyActionsInner
func BulkCreateActionBulkTaskInstanceBodyAsBulkBodyBulkTaskInstanceBodyActionsInner(v *BulkCreateActionBulkTaskInstanceBody) BulkBodyBulkTaskInstanceBodyActionsInner {
	return BulkBodyBulkTaskInstanceBodyActionsInner{
		BulkCreateActionBulkTaskInstanceBody: v,
	}
}

// BulkDeleteActionBulkTaskInstanceBodyAsBulkBodyBulkTaskInstanceBodyActionsInner is a convenience function that returns BulkDeleteActionBulkTaskInstanceBody wrapped in BulkBodyBulkTaskInstanceBodyActionsInner
func BulkDeleteActionBulkTaskInstanceBodyAsBulkBodyBulkTaskInstanceBodyActionsInner(v *BulkDeleteActionBulkTaskInstanceBody) BulkBodyBulkTaskInstanceBodyActionsInner {
	return BulkBodyBulkTaskInstanceBodyActionsInner{
		BulkDeleteActionBulkTaskInstanceBody: v,
	}
}

// BulkUpdateActionBulkTaskInstanceBodyAsBulkBodyBulkTaskInstanceBodyActionsInner is a convenience function that returns BulkUpdateActionBulkTaskInstanceBody wrapped in BulkBodyBulkTaskInstanceBodyActionsInner
func BulkUpdateActionBulkTaskInstanceBodyAsBulkBodyBulkTaskInstanceBodyActionsInner(v *BulkUpdateActionBulkTaskInstanceBody) BulkBodyBulkTaskInstanceBodyActionsInner {
	return BulkBodyBulkTaskInstanceBodyActionsInner{
		BulkUpdateActionBulkTaskInstanceBody: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkBodyBulkTaskInstanceBodyActionsInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BulkCreateActionBulkTaskInstanceBody
	err = newStrictDecoder(data).Decode(&dst.BulkCreateActionBulkTaskInstanceBody)
	if err == nil {
		jsonBulkCreateActionBulkTaskInstanceBody, _ := json.Marshal(dst.BulkCreateActionBulkTaskInstanceBody)
		if string(jsonBulkCreateActionBulkTaskInstanceBody) == "{}" { // empty struct
			dst.BulkCreateActionBulkTaskInstanceBody = nil
		} else {
			if err = validator.Validate(dst.BulkCreateActionBulkTaskInstanceBody); err != nil {
				dst.BulkCreateActionBulkTaskInstanceBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.BulkCreateActionBulkTaskInstanceBody = nil
	}

	// try to unmarshal data into BulkDeleteActionBulkTaskInstanceBody
	err = newStrictDecoder(data).Decode(&dst.BulkDeleteActionBulkTaskInstanceBody)
	if err == nil {
		jsonBulkDeleteActionBulkTaskInstanceBody, _ := json.Marshal(dst.BulkDeleteActionBulkTaskInstanceBody)
		if string(jsonBulkDeleteActionBulkTaskInstanceBody) == "{}" { // empty struct
			dst.BulkDeleteActionBulkTaskInstanceBody = nil
		} else {
			if err = validator.Validate(dst.BulkDeleteActionBulkTaskInstanceBody); err != nil {
				dst.BulkDeleteActionBulkTaskInstanceBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.BulkDeleteActionBulkTaskInstanceBody = nil
	}

	// try to unmarshal data into BulkUpdateActionBulkTaskInstanceBody
	err = newStrictDecoder(data).Decode(&dst.BulkUpdateActionBulkTaskInstanceBody)
	if err == nil {
		jsonBulkUpdateActionBulkTaskInstanceBody, _ := json.Marshal(dst.BulkUpdateActionBulkTaskInstanceBody)
		if string(jsonBulkUpdateActionBulkTaskInstanceBody) == "{}" { // empty struct
			dst.BulkUpdateActionBulkTaskInstanceBody = nil
		} else {
			if err = validator.Validate(dst.BulkUpdateActionBulkTaskInstanceBody); err != nil {
				dst.BulkUpdateActionBulkTaskInstanceBody = nil
			} else {
				match++
			}
		}
	} else {
		dst.BulkUpdateActionBulkTaskInstanceBody = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BulkCreateActionBulkTaskInstanceBody = nil
		dst.BulkDeleteActionBulkTaskInstanceBody = nil
		dst.BulkUpdateActionBulkTaskInstanceBody = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkBodyBulkTaskInstanceBodyActionsInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BulkBodyBulkTaskInstanceBodyActionsInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkBodyBulkTaskInstanceBodyActionsInner) MarshalJSON() ([]byte, error) {
	if src.BulkCreateActionBulkTaskInstanceBody != nil {
		return json.Marshal(&src.BulkCreateActionBulkTaskInstanceBody)
	}

	if src.BulkDeleteActionBulkTaskInstanceBody != nil {
		return json.Marshal(&src.BulkDeleteActionBulkTaskInstanceBody)
	}

	if src.BulkUpdateActionBulkTaskInstanceBody != nil {
		return json.Marshal(&src.BulkUpdateActionBulkTaskInstanceBody)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkBodyBulkTaskInstanceBodyActionsInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BulkCreateActionBulkTaskInstanceBody != nil {
		return obj.BulkCreateActionBulkTaskInstanceBody
	}

	if obj.BulkDeleteActionBulkTaskInstanceBody != nil {
		return obj.BulkDeleteActionBulkTaskInstanceBody
	}

	if obj.BulkUpdateActionBulkTaskInstanceBody != nil {
		return obj.BulkUpdateActionBulkTaskInstanceBody
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkBodyBulkTaskInstanceBodyActionsInner) GetActualInstanceValue() (interface{}) {
	if obj.BulkCreateActionBulkTaskInstanceBody != nil {
		return *obj.BulkCreateActionBulkTaskInstanceBody
	}

	if obj.BulkDeleteActionBulkTaskInstanceBody != nil {
		return *obj.BulkDeleteActionBulkTaskInstanceBody
	}

	if obj.BulkUpdateActionBulkTaskInstanceBody != nil {
		return *obj.BulkUpdateActionBulkTaskInstanceBody
	}

	// all schemas are nil
	return nil
}

type NullableBulkBodyBulkTaskInstanceBodyActionsInner struct {
	value *BulkBodyBulkTaskInstanceBodyActionsInner
	isSet bool
}

func (v NullableBulkBodyBulkTaskInstanceBodyActionsInner) Get() *BulkBodyBulkTaskInstanceBodyActionsInner {
	return v.value
}

func (v *NullableBulkBodyBulkTaskInstanceBodyActionsInner) Set(val *BulkBodyBulkTaskInstanceBodyActionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkBodyBulkTaskInstanceBodyActionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkBodyBulkTaskInstanceBodyActionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkBodyBulkTaskInstanceBodyActionsInner(val *BulkBodyBulkTaskInstanceBodyActionsInner) *NullableBulkBodyBulkTaskInstanceBodyActionsInner {
	return &NullableBulkBodyBulkTaskInstanceBodyActionsInner{value: val, isSet: true}
}

func (v NullableBulkBodyBulkTaskInstanceBodyActionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkBodyBulkTaskInstanceBodyActionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


