/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
)

// checks if the DAGRunClearBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGRunClearBody{}

// DAGRunClearBody DAG Run serializer for clear endpoint body.
type DAGRunClearBody struct {
	DryRun *bool `json:"dry_run,omitempty"`
	OnlyFailed *bool `json:"only_failed,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DAGRunClearBody DAGRunClearBody

// NewDAGRunClearBody instantiates a new DAGRunClearBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGRunClearBody() *DAGRunClearBody {
	this := DAGRunClearBody{}
	var dryRun bool = true
	this.DryRun = &dryRun
	var onlyFailed bool = false
	this.OnlyFailed = &onlyFailed
	return &this
}

// NewDAGRunClearBodyWithDefaults instantiates a new DAGRunClearBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGRunClearBodyWithDefaults() *DAGRunClearBody {
	this := DAGRunClearBody{}
	var dryRun bool = true
	this.DryRun = &dryRun
	var onlyFailed bool = false
	this.OnlyFailed = &onlyFailed
	return &this
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *DAGRunClearBody) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunClearBody) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *DAGRunClearBody) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *DAGRunClearBody) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetOnlyFailed returns the OnlyFailed field value if set, zero value otherwise.
func (o *DAGRunClearBody) GetOnlyFailed() bool {
	if o == nil || IsNil(o.OnlyFailed) {
		var ret bool
		return ret
	}
	return *o.OnlyFailed
}

// GetOnlyFailedOk returns a tuple with the OnlyFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunClearBody) GetOnlyFailedOk() (*bool, bool) {
	if o == nil || IsNil(o.OnlyFailed) {
		return nil, false
	}
	return o.OnlyFailed, true
}

// HasOnlyFailed returns a boolean if a field has been set.
func (o *DAGRunClearBody) HasOnlyFailed() bool {
	if o != nil && !IsNil(o.OnlyFailed) {
		return true
	}

	return false
}

// SetOnlyFailed gets a reference to the given bool and assigns it to the OnlyFailed field.
func (o *DAGRunClearBody) SetOnlyFailed(v bool) {
	o.OnlyFailed = &v
}

func (o DAGRunClearBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGRunClearBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DryRun) {
		toSerialize["dry_run"] = o.DryRun
	}
	if !IsNil(o.OnlyFailed) {
		toSerialize["only_failed"] = o.OnlyFailed
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DAGRunClearBody) UnmarshalJSON(data []byte) (err error) {
	varDAGRunClearBody := _DAGRunClearBody{}

	err = json.Unmarshal(data, &varDAGRunClearBody)

	if err != nil {
		return err
	}

	*o = DAGRunClearBody(varDAGRunClearBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dry_run")
		delete(additionalProperties, "only_failed")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDAGRunClearBody struct {
	value *DAGRunClearBody
	isSet bool
}

func (v NullableDAGRunClearBody) Get() *DAGRunClearBody {
	return v.value
}

func (v *NullableDAGRunClearBody) Set(val *DAGRunClearBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGRunClearBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGRunClearBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGRunClearBody(val *DAGRunClearBody) *NullableDAGRunClearBody {
	return &NullableDAGRunClearBody{value: val, isSet: true}
}

func (v NullableDAGRunClearBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGRunClearBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


