/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkBodyVariableBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkBodyVariableBody{}

// BulkBodyVariableBody struct for BulkBodyVariableBody
type BulkBodyVariableBody struct {
	Actions []BulkBodyVariableBodyActionsInner `json:"actions"`
	AdditionalProperties map[string]interface{}
}

type _BulkBodyVariableBody BulkBodyVariableBody

// NewBulkBodyVariableBody instantiates a new BulkBodyVariableBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkBodyVariableBody(actions []BulkBodyVariableBodyActionsInner) *BulkBodyVariableBody {
	this := BulkBodyVariableBody{}
	this.Actions = actions
	return &this
}

// NewBulkBodyVariableBodyWithDefaults instantiates a new BulkBodyVariableBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkBodyVariableBodyWithDefaults() *BulkBodyVariableBody {
	this := BulkBodyVariableBody{}
	return &this
}

// GetActions returns the Actions field value
func (o *BulkBodyVariableBody) GetActions() []BulkBodyVariableBodyActionsInner {
	if o == nil {
		var ret []BulkBodyVariableBodyActionsInner
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *BulkBodyVariableBody) GetActionsOk() ([]BulkBodyVariableBodyActionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *BulkBodyVariableBody) SetActions(v []BulkBodyVariableBodyActionsInner) {
	o.Actions = v
}

func (o BulkBodyVariableBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkBodyVariableBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["actions"] = o.Actions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkBodyVariableBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkBodyVariableBody := _BulkBodyVariableBody{}

	err = json.Unmarshal(data, &varBulkBodyVariableBody)

	if err != nil {
		return err
	}

	*o = BulkBodyVariableBody(varBulkBodyVariableBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "actions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkBodyVariableBody struct {
	value *BulkBodyVariableBody
	isSet bool
}

func (v NullableBulkBodyVariableBody) Get() *BulkBodyVariableBody {
	return v.value
}

func (v *NullableBulkBodyVariableBody) Set(val *BulkBodyVariableBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkBodyVariableBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkBodyVariableBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkBodyVariableBody(val *BulkBodyVariableBody) *NullableBulkBodyVariableBody {
	return &NullableBulkBodyVariableBody{value: val, isSet: true}
}

func (v NullableBulkBodyVariableBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkBodyVariableBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


