/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DAGRunCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGRunCollectionResponse{}

// DAGRunCollectionResponse DAG Run Collection serializer for responses.
type DAGRunCollectionResponse struct {
	DagRuns []DAGRunResponse `json:"dag_runs"`
	TotalEntries int32 `json:"total_entries"`
}

type _DAGRunCollectionResponse DAGRunCollectionResponse

// NewDAGRunCollectionResponse instantiates a new DAGRunCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGRunCollectionResponse(dagRuns []DAGRunResponse, totalEntries int32) *DAGRunCollectionResponse {
	this := DAGRunCollectionResponse{}
	this.DagRuns = dagRuns
	this.TotalEntries = totalEntries
	return &this
}

// NewDAGRunCollectionResponseWithDefaults instantiates a new DAGRunCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGRunCollectionResponseWithDefaults() *DAGRunCollectionResponse {
	this := DAGRunCollectionResponse{}
	return &this
}

// GetDagRuns returns the DagRuns field value
func (o *DAGRunCollectionResponse) GetDagRuns() []DAGRunResponse {
	if o == nil {
		var ret []DAGRunResponse
		return ret
	}

	return o.DagRuns
}

// GetDagRunsOk returns a tuple with the DagRuns field value
// and a boolean to check if the value has been set.
func (o *DAGRunCollectionResponse) GetDagRunsOk() ([]DAGRunResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.DagRuns, true
}

// SetDagRuns sets field value
func (o *DAGRunCollectionResponse) SetDagRuns(v []DAGRunResponse) {
	o.DagRuns = v
}

// GetTotalEntries returns the TotalEntries field value
func (o *DAGRunCollectionResponse) GetTotalEntries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value
// and a boolean to check if the value has been set.
func (o *DAGRunCollectionResponse) GetTotalEntriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEntries, true
}

// SetTotalEntries sets field value
func (o *DAGRunCollectionResponse) SetTotalEntries(v int32) {
	o.TotalEntries = v
}

func (o DAGRunCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGRunCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dag_runs"] = o.DagRuns
	toSerialize["total_entries"] = o.TotalEntries
	return toSerialize, nil
}

func (o *DAGRunCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dag_runs",
		"total_entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDAGRunCollectionResponse := _DAGRunCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDAGRunCollectionResponse)

	if err != nil {
		return err
	}

	*o = DAGRunCollectionResponse(varDAGRunCollectionResponse)

	return err
}

type NullableDAGRunCollectionResponse struct {
	value *DAGRunCollectionResponse
	isSet bool
}

func (v NullableDAGRunCollectionResponse) Get() *DAGRunCollectionResponse {
	return v.value
}

func (v *NullableDAGRunCollectionResponse) Set(val *DAGRunCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGRunCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGRunCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGRunCollectionResponse(val *DAGRunCollectionResponse) *NullableDAGRunCollectionResponse {
	return &NullableDAGRunCollectionResponse{value: val, isSet: true}
}

func (v NullableDAGRunCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGRunCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


