/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"time"
)

// checks if the DAGRunsBatchBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DAGRunsBatchBody{}

// DAGRunsBatchBody List DAG Runs body for batch endpoint.
type DAGRunsBatchBody struct {
	OrderBy NullableString `json:"order_by,omitempty"`
	PageOffset *int32 `json:"page_offset,omitempty"`
	PageLimit *int32 `json:"page_limit,omitempty"`
	DagIds []string `json:"dag_ids,omitempty"`
	States []DagRunState `json:"states,omitempty"`
	RunAfterGte NullableTime `json:"run_after_gte,omitempty"`
	RunAfterLte NullableTime `json:"run_after_lte,omitempty"`
	LogicalDateGte NullableTime `json:"logical_date_gte,omitempty"`
	LogicalDateLte NullableTime `json:"logical_date_lte,omitempty"`
	StartDateGte NullableTime `json:"start_date_gte,omitempty"`
	StartDateLte NullableTime `json:"start_date_lte,omitempty"`
	EndDateGte NullableTime `json:"end_date_gte,omitempty"`
	EndDateLte NullableTime `json:"end_date_lte,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DAGRunsBatchBody DAGRunsBatchBody

// NewDAGRunsBatchBody instantiates a new DAGRunsBatchBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDAGRunsBatchBody() *DAGRunsBatchBody {
	this := DAGRunsBatchBody{}
	var pageOffset int32 = 0
	this.PageOffset = &pageOffset
	var pageLimit int32 = 100
	this.PageLimit = &pageLimit
	return &this
}

// NewDAGRunsBatchBodyWithDefaults instantiates a new DAGRunsBatchBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDAGRunsBatchBodyWithDefaults() *DAGRunsBatchBody {
	this := DAGRunsBatchBody{}
	var pageOffset int32 = 0
	this.PageOffset = &pageOffset
	var pageLimit int32 = 100
	this.PageLimit = &pageLimit
	return &this
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetOrderBy() string {
	if o == nil || IsNil(o.OrderBy.Get()) {
		var ret string
		return ret
	}
	return *o.OrderBy.Get()
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetOrderByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderBy.Get(), o.OrderBy.IsSet()
}

// HasOrderBy returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasOrderBy() bool {
	if o != nil && o.OrderBy.IsSet() {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given NullableString and assigns it to the OrderBy field.
func (o *DAGRunsBatchBody) SetOrderBy(v string) {
	o.OrderBy.Set(&v)
}
// SetOrderByNil sets the value for OrderBy to be an explicit nil
func (o *DAGRunsBatchBody) SetOrderByNil() {
	o.OrderBy.Set(nil)
}

// UnsetOrderBy ensures that no value is present for OrderBy, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetOrderBy() {
	o.OrderBy.Unset()
}

// GetPageOffset returns the PageOffset field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetPageOffset() int32 {
	if o == nil || IsNil(o.PageOffset) {
		var ret int32
		return ret
	}
	return *o.PageOffset
}

// GetPageOffsetOk returns a tuple with the PageOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetPageOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.PageOffset) {
		return nil, false
	}
	return o.PageOffset, true
}

// HasPageOffset returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasPageOffset() bool {
	if o != nil && !IsNil(o.PageOffset) {
		return true
	}

	return false
}

// SetPageOffset gets a reference to the given int32 and assigns it to the PageOffset field.
func (o *DAGRunsBatchBody) SetPageOffset(v int32) {
	o.PageOffset = &v
}

// GetPageLimit returns the PageLimit field value if set, zero value otherwise.
func (o *DAGRunsBatchBody) GetPageLimit() int32 {
	if o == nil || IsNil(o.PageLimit) {
		var ret int32
		return ret
	}
	return *o.PageLimit
}

// GetPageLimitOk returns a tuple with the PageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DAGRunsBatchBody) GetPageLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.PageLimit) {
		return nil, false
	}
	return o.PageLimit, true
}

// HasPageLimit returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasPageLimit() bool {
	if o != nil && !IsNil(o.PageLimit) {
		return true
	}

	return false
}

// SetPageLimit gets a reference to the given int32 and assigns it to the PageLimit field.
func (o *DAGRunsBatchBody) SetPageLimit(v int32) {
	o.PageLimit = &v
}

// GetDagIds returns the DagIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetDagIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.DagIds
}

// GetDagIdsOk returns a tuple with the DagIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetDagIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DagIds) {
		return nil, false
	}
	return o.DagIds, true
}

// HasDagIds returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasDagIds() bool {
	if o != nil && !IsNil(o.DagIds) {
		return true
	}

	return false
}

// SetDagIds gets a reference to the given []string and assigns it to the DagIds field.
func (o *DAGRunsBatchBody) SetDagIds(v []string) {
	o.DagIds = v
}

// GetStates returns the States field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetStates() []DagRunState {
	if o == nil {
		var ret []DagRunState
		return ret
	}
	return o.States
}

// GetStatesOk returns a tuple with the States field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetStatesOk() ([]DagRunState, bool) {
	if o == nil || IsNil(o.States) {
		return nil, false
	}
	return o.States, true
}

// HasStates returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStates() bool {
	if o != nil && !IsNil(o.States) {
		return true
	}

	return false
}

// SetStates gets a reference to the given []DagRunState and assigns it to the States field.
func (o *DAGRunsBatchBody) SetStates(v []DagRunState) {
	o.States = v
}

// GetRunAfterGte returns the RunAfterGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetRunAfterGte() time.Time {
	if o == nil || IsNil(o.RunAfterGte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterGte.Get()
}

// GetRunAfterGteOk returns a tuple with the RunAfterGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetRunAfterGteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunAfterGte.Get(), o.RunAfterGte.IsSet()
}

// HasRunAfterGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterGte() bool {
	if o != nil && o.RunAfterGte.IsSet() {
		return true
	}

	return false
}

// SetRunAfterGte gets a reference to the given NullableTime and assigns it to the RunAfterGte field.
func (o *DAGRunsBatchBody) SetRunAfterGte(v time.Time) {
	o.RunAfterGte.Set(&v)
}
// SetRunAfterGteNil sets the value for RunAfterGte to be an explicit nil
func (o *DAGRunsBatchBody) SetRunAfterGteNil() {
	o.RunAfterGte.Set(nil)
}

// UnsetRunAfterGte ensures that no value is present for RunAfterGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetRunAfterGte() {
	o.RunAfterGte.Unset()
}

// GetRunAfterLte returns the RunAfterLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetRunAfterLte() time.Time {
	if o == nil || IsNil(o.RunAfterLte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RunAfterLte.Get()
}

// GetRunAfterLteOk returns a tuple with the RunAfterLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetRunAfterLteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunAfterLte.Get(), o.RunAfterLte.IsSet()
}

// HasRunAfterLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasRunAfterLte() bool {
	if o != nil && o.RunAfterLte.IsSet() {
		return true
	}

	return false
}

// SetRunAfterLte gets a reference to the given NullableTime and assigns it to the RunAfterLte field.
func (o *DAGRunsBatchBody) SetRunAfterLte(v time.Time) {
	o.RunAfterLte.Set(&v)
}
// SetRunAfterLteNil sets the value for RunAfterLte to be an explicit nil
func (o *DAGRunsBatchBody) SetRunAfterLteNil() {
	o.RunAfterLte.Set(nil)
}

// UnsetRunAfterLte ensures that no value is present for RunAfterLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetRunAfterLte() {
	o.RunAfterLte.Unset()
}

// GetLogicalDateGte returns the LogicalDateGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetLogicalDateGte() time.Time {
	if o == nil || IsNil(o.LogicalDateGte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateGte.Get()
}

// GetLogicalDateGteOk returns a tuple with the LogicalDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetLogicalDateGteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalDateGte.Get(), o.LogicalDateGte.IsSet()
}

// HasLogicalDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateGte() bool {
	if o != nil && o.LogicalDateGte.IsSet() {
		return true
	}

	return false
}

// SetLogicalDateGte gets a reference to the given NullableTime and assigns it to the LogicalDateGte field.
func (o *DAGRunsBatchBody) SetLogicalDateGte(v time.Time) {
	o.LogicalDateGte.Set(&v)
}
// SetLogicalDateGteNil sets the value for LogicalDateGte to be an explicit nil
func (o *DAGRunsBatchBody) SetLogicalDateGteNil() {
	o.LogicalDateGte.Set(nil)
}

// UnsetLogicalDateGte ensures that no value is present for LogicalDateGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetLogicalDateGte() {
	o.LogicalDateGte.Unset()
}

// GetLogicalDateLte returns the LogicalDateLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetLogicalDateLte() time.Time {
	if o == nil || IsNil(o.LogicalDateLte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LogicalDateLte.Get()
}

// GetLogicalDateLteOk returns a tuple with the LogicalDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetLogicalDateLteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalDateLte.Get(), o.LogicalDateLte.IsSet()
}

// HasLogicalDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasLogicalDateLte() bool {
	if o != nil && o.LogicalDateLte.IsSet() {
		return true
	}

	return false
}

// SetLogicalDateLte gets a reference to the given NullableTime and assigns it to the LogicalDateLte field.
func (o *DAGRunsBatchBody) SetLogicalDateLte(v time.Time) {
	o.LogicalDateLte.Set(&v)
}
// SetLogicalDateLteNil sets the value for LogicalDateLte to be an explicit nil
func (o *DAGRunsBatchBody) SetLogicalDateLteNil() {
	o.LogicalDateLte.Set(nil)
}

// UnsetLogicalDateLte ensures that no value is present for LogicalDateLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetLogicalDateLte() {
	o.LogicalDateLte.Unset()
}

// GetStartDateGte returns the StartDateGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetStartDateGte() time.Time {
	if o == nil || IsNil(o.StartDateGte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDateGte.Get()
}

// GetStartDateGteOk returns a tuple with the StartDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetStartDateGteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDateGte.Get(), o.StartDateGte.IsSet()
}

// HasStartDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateGte() bool {
	if o != nil && o.StartDateGte.IsSet() {
		return true
	}

	return false
}

// SetStartDateGte gets a reference to the given NullableTime and assigns it to the StartDateGte field.
func (o *DAGRunsBatchBody) SetStartDateGte(v time.Time) {
	o.StartDateGte.Set(&v)
}
// SetStartDateGteNil sets the value for StartDateGte to be an explicit nil
func (o *DAGRunsBatchBody) SetStartDateGteNil() {
	o.StartDateGte.Set(nil)
}

// UnsetStartDateGte ensures that no value is present for StartDateGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetStartDateGte() {
	o.StartDateGte.Unset()
}

// GetStartDateLte returns the StartDateLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetStartDateLte() time.Time {
	if o == nil || IsNil(o.StartDateLte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartDateLte.Get()
}

// GetStartDateLteOk returns a tuple with the StartDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetStartDateLteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDateLte.Get(), o.StartDateLte.IsSet()
}

// HasStartDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasStartDateLte() bool {
	if o != nil && o.StartDateLte.IsSet() {
		return true
	}

	return false
}

// SetStartDateLte gets a reference to the given NullableTime and assigns it to the StartDateLte field.
func (o *DAGRunsBatchBody) SetStartDateLte(v time.Time) {
	o.StartDateLte.Set(&v)
}
// SetStartDateLteNil sets the value for StartDateLte to be an explicit nil
func (o *DAGRunsBatchBody) SetStartDateLteNil() {
	o.StartDateLte.Set(nil)
}

// UnsetStartDateLte ensures that no value is present for StartDateLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetStartDateLte() {
	o.StartDateLte.Unset()
}

// GetEndDateGte returns the EndDateGte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetEndDateGte() time.Time {
	if o == nil || IsNil(o.EndDateGte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDateGte.Get()
}

// GetEndDateGteOk returns a tuple with the EndDateGte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetEndDateGteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDateGte.Get(), o.EndDateGte.IsSet()
}

// HasEndDateGte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateGte() bool {
	if o != nil && o.EndDateGte.IsSet() {
		return true
	}

	return false
}

// SetEndDateGte gets a reference to the given NullableTime and assigns it to the EndDateGte field.
func (o *DAGRunsBatchBody) SetEndDateGte(v time.Time) {
	o.EndDateGte.Set(&v)
}
// SetEndDateGteNil sets the value for EndDateGte to be an explicit nil
func (o *DAGRunsBatchBody) SetEndDateGteNil() {
	o.EndDateGte.Set(nil)
}

// UnsetEndDateGte ensures that no value is present for EndDateGte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetEndDateGte() {
	o.EndDateGte.Unset()
}

// GetEndDateLte returns the EndDateLte field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DAGRunsBatchBody) GetEndDateLte() time.Time {
	if o == nil || IsNil(o.EndDateLte.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndDateLte.Get()
}

// GetEndDateLteOk returns a tuple with the EndDateLte field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DAGRunsBatchBody) GetEndDateLteOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDateLte.Get(), o.EndDateLte.IsSet()
}

// HasEndDateLte returns a boolean if a field has been set.
func (o *DAGRunsBatchBody) HasEndDateLte() bool {
	if o != nil && o.EndDateLte.IsSet() {
		return true
	}

	return false
}

// SetEndDateLte gets a reference to the given NullableTime and assigns it to the EndDateLte field.
func (o *DAGRunsBatchBody) SetEndDateLte(v time.Time) {
	o.EndDateLte.Set(&v)
}
// SetEndDateLteNil sets the value for EndDateLte to be an explicit nil
func (o *DAGRunsBatchBody) SetEndDateLteNil() {
	o.EndDateLte.Set(nil)
}

// UnsetEndDateLte ensures that no value is present for EndDateLte, not even an explicit nil
func (o *DAGRunsBatchBody) UnsetEndDateLte() {
	o.EndDateLte.Unset()
}

func (o DAGRunsBatchBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DAGRunsBatchBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OrderBy.IsSet() {
		toSerialize["order_by"] = o.OrderBy.Get()
	}
	if !IsNil(o.PageOffset) {
		toSerialize["page_offset"] = o.PageOffset
	}
	if !IsNil(o.PageLimit) {
		toSerialize["page_limit"] = o.PageLimit
	}
	if o.DagIds != nil {
		toSerialize["dag_ids"] = o.DagIds
	}
	if o.States != nil {
		toSerialize["states"] = o.States
	}
	if o.RunAfterGte.IsSet() {
		toSerialize["run_after_gte"] = o.RunAfterGte.Get()
	}
	if o.RunAfterLte.IsSet() {
		toSerialize["run_after_lte"] = o.RunAfterLte.Get()
	}
	if o.LogicalDateGte.IsSet() {
		toSerialize["logical_date_gte"] = o.LogicalDateGte.Get()
	}
	if o.LogicalDateLte.IsSet() {
		toSerialize["logical_date_lte"] = o.LogicalDateLte.Get()
	}
	if o.StartDateGte.IsSet() {
		toSerialize["start_date_gte"] = o.StartDateGte.Get()
	}
	if o.StartDateLte.IsSet() {
		toSerialize["start_date_lte"] = o.StartDateLte.Get()
	}
	if o.EndDateGte.IsSet() {
		toSerialize["end_date_gte"] = o.EndDateGte.Get()
	}
	if o.EndDateLte.IsSet() {
		toSerialize["end_date_lte"] = o.EndDateLte.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DAGRunsBatchBody) UnmarshalJSON(data []byte) (err error) {
	varDAGRunsBatchBody := _DAGRunsBatchBody{}

	err = json.Unmarshal(data, &varDAGRunsBatchBody)

	if err != nil {
		return err
	}

	*o = DAGRunsBatchBody(varDAGRunsBatchBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "order_by")
		delete(additionalProperties, "page_offset")
		delete(additionalProperties, "page_limit")
		delete(additionalProperties, "dag_ids")
		delete(additionalProperties, "states")
		delete(additionalProperties, "run_after_gte")
		delete(additionalProperties, "run_after_lte")
		delete(additionalProperties, "logical_date_gte")
		delete(additionalProperties, "logical_date_lte")
		delete(additionalProperties, "start_date_gte")
		delete(additionalProperties, "start_date_lte")
		delete(additionalProperties, "end_date_gte")
		delete(additionalProperties, "end_date_lte")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDAGRunsBatchBody struct {
	value *DAGRunsBatchBody
	isSet bool
}

func (v NullableDAGRunsBatchBody) Get() *DAGRunsBatchBody {
	return v.value
}

func (v *NullableDAGRunsBatchBody) Set(val *DAGRunsBatchBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDAGRunsBatchBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDAGRunsBatchBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDAGRunsBatchBody(val *DAGRunsBatchBody) *NullableDAGRunsBatchBody {
	return &NullableDAGRunsBatchBody{value: val, isSet: true}
}

func (v NullableDAGRunsBatchBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDAGRunsBatchBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


