/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"fmt"
)

// checks if the PoolBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoolBody{}

// PoolBody Pool serializer for post bodies.
type PoolBody struct {
	Name string `json:"name"`
	Slots int32 `json:"slots"`
	Description NullableString `json:"description,omitempty"`
	IncludeDeferred *bool `json:"include_deferred,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PoolBody PoolBody

// NewPoolBody instantiates a new PoolBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolBody(name string, slots int32) *PoolBody {
	this := PoolBody{}
	this.Name = name
	this.Slots = slots
	var includeDeferred bool = false
	this.IncludeDeferred = &includeDeferred
	return &this
}

// NewPoolBodyWithDefaults instantiates a new PoolBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolBodyWithDefaults() *PoolBody {
	this := PoolBody{}
	var includeDeferred bool = false
	this.IncludeDeferred = &includeDeferred
	return &this
}

// GetName returns the Name field value
func (o *PoolBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PoolBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PoolBody) SetName(v string) {
	o.Name = v
}

// GetSlots returns the Slots field value
func (o *PoolBody) GetSlots() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Slots
}

// GetSlotsOk returns a tuple with the Slots field value
// and a boolean to check if the value has been set.
func (o *PoolBody) GetSlotsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slots, true
}

// SetSlots sets field value
func (o *PoolBody) SetSlots(v int32) {
	o.Slots = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PoolBody) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PoolBody) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *PoolBody) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *PoolBody) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *PoolBody) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *PoolBody) UnsetDescription() {
	o.Description.Unset()
}

// GetIncludeDeferred returns the IncludeDeferred field value if set, zero value otherwise.
func (o *PoolBody) GetIncludeDeferred() bool {
	if o == nil || IsNil(o.IncludeDeferred) {
		var ret bool
		return ret
	}
	return *o.IncludeDeferred
}

// GetIncludeDeferredOk returns a tuple with the IncludeDeferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolBody) GetIncludeDeferredOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeDeferred) {
		return nil, false
	}
	return o.IncludeDeferred, true
}

// HasIncludeDeferred returns a boolean if a field has been set.
func (o *PoolBody) HasIncludeDeferred() bool {
	if o != nil && !IsNil(o.IncludeDeferred) {
		return true
	}

	return false
}

// SetIncludeDeferred gets a reference to the given bool and assigns it to the IncludeDeferred field.
func (o *PoolBody) SetIncludeDeferred(v bool) {
	o.IncludeDeferred = &v
}

func (o PoolBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoolBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["slots"] = o.Slots
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.IncludeDeferred) {
		toSerialize["include_deferred"] = o.IncludeDeferred
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PoolBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"slots",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoolBody := _PoolBody{}

	err = json.Unmarshal(data, &varPoolBody)

	if err != nil {
		return err
	}

	*o = PoolBody(varPoolBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "slots")
		delete(additionalProperties, "description")
		delete(additionalProperties, "include_deferred")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePoolBody struct {
	value *PoolBody
	isSet bool
}

func (v NullablePoolBody) Get() *PoolBody {
	return v.value
}

func (v *NullablePoolBody) Set(val *PoolBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolBody(val *PoolBody) *NullablePoolBody {
	return &NullablePoolBody{value: val, isSet: true}
}

func (v NullablePoolBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


