/*
Airflow API

Airflow API. All endpoints located under ``/api/v2`` can be used safely, are stable and backward compatible. Endpoints located under ``/ui`` are dedicated to the UI and are subject to breaking change depending on the need of the frontend. Users should not rely on those but use the public ones instead.

API version: 2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airflow

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TaskInstanceCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskInstanceCollectionResponse{}

// TaskInstanceCollectionResponse Task Instance Collection serializer for responses.
type TaskInstanceCollectionResponse struct {
	TaskInstances []TaskInstanceResponse `json:"task_instances"`
	TotalEntries int32 `json:"total_entries"`
}

type _TaskInstanceCollectionResponse TaskInstanceCollectionResponse

// NewTaskInstanceCollectionResponse instantiates a new TaskInstanceCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskInstanceCollectionResponse(taskInstances []TaskInstanceResponse, totalEntries int32) *TaskInstanceCollectionResponse {
	this := TaskInstanceCollectionResponse{}
	this.TaskInstances = taskInstances
	this.TotalEntries = totalEntries
	return &this
}

// NewTaskInstanceCollectionResponseWithDefaults instantiates a new TaskInstanceCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskInstanceCollectionResponseWithDefaults() *TaskInstanceCollectionResponse {
	this := TaskInstanceCollectionResponse{}
	return &this
}

// GetTaskInstances returns the TaskInstances field value
func (o *TaskInstanceCollectionResponse) GetTaskInstances() []TaskInstanceResponse {
	if o == nil {
		var ret []TaskInstanceResponse
		return ret
	}

	return o.TaskInstances
}

// GetTaskInstancesOk returns a tuple with the TaskInstances field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceCollectionResponse) GetTaskInstancesOk() ([]TaskInstanceResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaskInstances, true
}

// SetTaskInstances sets field value
func (o *TaskInstanceCollectionResponse) SetTaskInstances(v []TaskInstanceResponse) {
	o.TaskInstances = v
}

// GetTotalEntries returns the TotalEntries field value
func (o *TaskInstanceCollectionResponse) GetTotalEntries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEntries
}

// GetTotalEntriesOk returns a tuple with the TotalEntries field value
// and a boolean to check if the value has been set.
func (o *TaskInstanceCollectionResponse) GetTotalEntriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEntries, true
}

// SetTotalEntries sets field value
func (o *TaskInstanceCollectionResponse) SetTotalEntries(v int32) {
	o.TotalEntries = v
}

func (o TaskInstanceCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskInstanceCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["task_instances"] = o.TaskInstances
	toSerialize["total_entries"] = o.TotalEntries
	return toSerialize, nil
}

func (o *TaskInstanceCollectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"task_instances",
		"total_entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskInstanceCollectionResponse := _TaskInstanceCollectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaskInstanceCollectionResponse)

	if err != nil {
		return err
	}

	*o = TaskInstanceCollectionResponse(varTaskInstanceCollectionResponse)

	return err
}

type NullableTaskInstanceCollectionResponse struct {
	value *TaskInstanceCollectionResponse
	isSet bool
}

func (v NullableTaskInstanceCollectionResponse) Get() *TaskInstanceCollectionResponse {
	return v.value
}

func (v *NullableTaskInstanceCollectionResponse) Set(val *TaskInstanceCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskInstanceCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskInstanceCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskInstanceCollectionResponse(val *TaskInstanceCollectionResponse) *NullableTaskInstanceCollectionResponse {
	return &NullableTaskInstanceCollectionResponse{value: val, isSet: true}
}

func (v NullableTaskInstanceCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskInstanceCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


